export const DiagramSetting = {
	keyStart: '_s',
	keyEnd: '_n',
	keyTip: '_t',
	font: '12px Microsoft YaHei',
	groupFont: '12px Microsoft YaHei',
	tipFont: '12px Microsoft YaHei',
	groupTipFont: '12px Microsoft YaHei',
	moveNode: true,
	moveLoop: true,
	moveCond: true,
	moveCondBranch: false,
	renameable: false,
	showKey: false,
	showGuid: false,
	showLabel: '',
	parameter1: 4,
	parameter1Group: 2,
	padding: 2,
	layerSpacing: 20,
	startWidth: 16,
	startInWidth: 8,
	endWidth: 16,
	endInWidth: 8,
	iconWidth: 14,
	iconInWidth: 7,
	linkIconWidth: 16,
	linkIconInWidth: 8,
	nodeWith: 180,
	nodeHeight: 20,
	groupWith: 160,
	ConditionWidth: 140,
	groupHeight: 0,
	linkOpacity: 1,
	spotOpacity: 0,
	openWidth: 2
};
